"use client";

import { useCallback, useEffect, useState } from "react";

type Project = { id: number; project_code: string; project_name: string; is_active: boolean; updated_at: string };
type Vendor = { id: number; vendor_name: string; vendor_code: number; is_active: boolean; updated_at: string };
type Settings = { delivery_warning_days: number; bond_critical_days: number; bond_warning_days: number } | null;
type Data = { projects: Project[]; vendors: Vendor[]; settings: Settings; permissions: { isAdmin: boolean } };

export default function MasterDataManager() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/master-data", { cache: "no-store" }); const payload = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Unable to load master data."); setData(payload); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load master data."); } finally { setLoading(false); } }, []);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void refresh(); }, [refresh]);
  async function request(body: Record<string, unknown>, method = "POST") { setError(""); const response = await fetch("/api/master-data", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Unable to save master data."); setNotice("Saved."); await refresh(); }
  if (loading && !data) return <div className="loading-table">Loading master data…</div>;
  if (error && !data) return <div className="page-error"><h1>Master data unavailable</h1><p>{error}</p><button className="button button-primary" onClick={() => void refresh()}>Retry</button></div>;
  if (!data) return null;
  return <><section className="page-header"><div><p className="eyebrow">Workspace standards</p><h1>Master Data</h1><p>Projects, vendors, category values, and operational thresholds.</p></div><span className={`status-badge ${data.permissions.isAdmin ? "status-valid" : "status-n/a"}`}>{data.permissions.isAdmin ? "Administrator access" : "Read only"}</span></section>{notice && <div className="notice">{notice}</div>}{error && <div className="form-error">{error}</div>}<div className="master-grid"><MasterTable title="Project codes" description="Inactive projects remain visible on historic POs, but should not be used for new ones." isAdmin={data.permissions.isAdmin} rows={data.projects} columns={[["Code", (item: Project) => item.project_code], ["Project name", (item: Project) => item.project_name || "—"]]} onToggle={(item) => void request({ kind: "project", id: item.id, isActive: !item.is_active }, "PUT")} form={<ProjectForm onSubmit={(body) => request(body)} />} /><MasterTable title="Vendors" description="Vendor code is a mandatory whole number. Inactive vendors remain visible on historic POs." isAdmin={data.permissions.isAdmin} rows={data.vendors} columns={[["Code", (item: Vendor) => String(item.vendor_code)], ["Vendor", (item: Vendor) => item.vendor_name]]} onToggle={(item) => void request({ kind: "vendor", id: item.id, isActive: !item.is_active }, "PUT")} form={<VendorForm onSubmit={(body) => request(body)} />} /></div><section className="panel settings-panel"><div><p className="eyebrow">Configuration</p><h2>Operational thresholds</h2><p>These settings drive consistent delivery and bond status calculations throughout the workspace.</p></div><SettingsForm settings={data.settings} isAdmin={data.permissions.isAdmin} onSubmit={(body) => request({ kind: "settings", ...body }, "PUT")} /><div className="static-master"><span>Purchasing groups: <b>ELE</b>, <b>INS</b>, <b>ROT</b>, <b>PRO</b></span><span>Payment terms: <b>T/T</b>, <b>SKBDN</b></span><span>Currencies: <b>IDR</b>, <b>USD</b>, <b>AUD</b>, <b>JPY</b>, <b>CNY</b>, <b>GBP</b>, <b>EUR</b></span><span>Bond types: <b>PB</b>, <b>WB</b></span></div></section></>;
}

function MasterTable<T extends { id: number; is_active: boolean }>({ title, description, isAdmin, rows, columns, onToggle, form }: { title: string; description: string; isAdmin: boolean; rows: T[]; columns: [string, (item: T) => string][]; onToggle: (item: T) => void; form: React.ReactNode }) { return <section className="panel master-panel"><div className="panel-heading"><div><h2>{title}</h2><p>{description}</p></div></div>{isAdmin && form}{rows.length ? <div className="table-scroll"><table><thead><tr>{columns.map(([label]) => <th key={label}>{label}</th>)}<th>Status</th>{isAdmin && <th />}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map(([label, render]) => <td key={label}>{render(row)}</td>)}<td><span className={`status-badge ${row.is_active ? "status-valid" : "status-n/a"}`}>{row.is_active ? "Active" : "Inactive"}</span></td>{isAdmin && <td><button className="row-action" onClick={() => onToggle(row)}>{row.is_active ? "Deactivate" : "Reactivate"}</button></td>}</tr>)}</tbody></table></div> : <div className="compact-empty"><strong>No {title.toLowerCase()} yet.</strong><p>Use the form above to create the first active record.</p></div>}</section>; }
function ProjectForm({ onSubmit }: { onSubmit: (body: Record<string, unknown>) => Promise<void> }) { const [code, setCode] = useState(""); const [name, setName] = useState(""); return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ kind: "project", projectCode: code, projectName: name }).then(() => { setCode(""); setName(""); }); }}><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Project code" required /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Project name" /><button className="button button-primary">Add project</button></form>; }
function VendorForm({ onSubmit }: { onSubmit: (body: Record<string, unknown>) => Promise<void> }) { const [name, setName] = useState(""); const [code, setCode] = useState(""); return <form className="inline-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ kind: "vendor", vendorName: name, vendorCode: code }).then(() => { setName(""); setCode(""); }); }}><input type="number" min="0" max="2147483647" step="1" inputMode="numeric" value={code} onChange={(event) => setCode(event.target.value)} placeholder="Vendor code" required /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Vendor name" required /><button className="button button-primary">Add vendor</button></form>; }
function SettingsForm({ settings, isAdmin, onSubmit }: { settings: Settings; isAdmin: boolean; onSubmit: (body: Record<string, unknown>) => Promise<void> }) { const [delivery, setDelivery] = useState(String(settings?.delivery_warning_days ?? 30)); const [critical, setCritical] = useState(String(settings?.bond_critical_days ?? 30)); const [warning, setWarning] = useState(String(settings?.bond_warning_days ?? 60)); return <form className="settings-form" onSubmit={(event) => { event.preventDefault(); void onSubmit({ deliveryWarningDays: Number(delivery), bondCriticalDays: Number(critical), bondWarningDays: Number(warning) }); }}><label>Delivery warning days<input type="number" min="1" max="365" value={delivery} disabled={!isAdmin} onChange={(event) => setDelivery(event.target.value)} /></label><label>Bond critical days<input type="number" min="1" max="365" value={critical} disabled={!isAdmin} onChange={(event) => setCritical(event.target.value)} /></label><label>Bond warning days<input type="number" min="1" max="365" value={warning} disabled={!isAdmin} onChange={(event) => setWarning(event.target.value)} /></label>{isAdmin && <button className="button button-primary">Save thresholds</button>}</form>; }
