"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { humanize, vendorTypes, type VendorSummary } from "../lib/vendors";

type Payload = { vendors: VendorSummary[]; total: number; filters: { categories: { id: string; name: string }[]; expertise: { id: string; name: string }[] } };
export default function VendorDirectory({ canEdit }: { canEdit: boolean }) {
  const [data, setData] = useState<Payload>({ vendors: [], total: 0, filters: { categories: [], expertise: [] } });
  const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState("active"); const [category, setCategory] = useState(""); const [expertise, setExpertise] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); setError(""); const params = new URLSearchParams({ q: query, type, status, category, expertise }); try { const response = await fetch(`/api/vendors?${params}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load vendors."); } finally { setLoading(false); } }, [query, type, status, category, expertise]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 250); return () => clearTimeout(timer); }, [refresh]);
  return <><section className="page-header vendor-heading"><div><p className="eyebrow">EPC procurement intelligence</p><h1>Vendor Directory</h1><p>Canonical companies, people, capabilities, aliases, and principal relationships in one searchable master.</p></div>{canEdit && <Link className="button button-primary" href="/vendors/new">Add vendor</Link>}</section>
    <section className="panel vendor-directory"><div className="vendor-filters"><label className="search-field"><span>Search vendor network</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, alias, PIC, email, phone, expertise, principal…" /></label><label>Vendor type<select value={type} onChange={e => setType(e.target.value)}><option value="">All types</option>{vendorTypes.map(item => <option key={item} value={item}>{humanize(item)}</option>)}</select></label><label>Category<select value={category} onChange={e => setCategory(e.target.value)}><option value="">All categories</option>{data.filters.categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Expertise<select value={expertise} onChange={e => setExpertise(e.target.value)}><option value="">All expertise</option>{data.filters.expertise.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Status<select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option>active</option><option>inactive</option><option>merged</option></select></label></div>
    <div className="directory-summary"><strong>{data.total}</strong> legal entities <span>•</span> Results include historical aliases and relationship names</div>{error ? <div className="error-state"><strong>Vendor directory unavailable.</strong><p>{error}</p></div> : loading ? <div className="loading-table">Searching vendor network…</div> : <div className="table-scroll"><table><thead><tr><th>Company</th><th>Type</th><th>Country</th><th>Contacts</th><th>Expertise</th><th>Relationships</th><th>Status</th></tr></thead><tbody>{data.vendors.map(vendor => <tr key={vendor.id}><td><Link className="vendor-link" href={`/vendors/${vendor.id}`}><strong>{vendor.display_name}</strong><span>{vendor.legal_name}</span></Link></td><td>{humanize(vendor.vendor_type)}</td><td>{vendor.country_code ?? "—"}</td><td>{vendor.vendor_contacts?.[0]?.count ?? 0}</td><td>{vendor.vendor_expertise?.[0]?.count ?? 0}</td><td>{vendor.vendor_relationships?.[0]?.count ?? 0}</td><td><span className={`status-badge status-${vendor.status === "active" ? "valid" : "n/a"}`}>{vendor.status}</span></td></tr>)}</tbody></table>{!data.vendors.length && <div className="empty-state"><h3>No vendors match these filters.</h3><p>Try a historical alias, contact detail, expertise, or principal name.</p></div>}</div>}</section></>;
}
