-- TPEC CM1 PO Monitoring: Supabase/Postgres schema and workspace controls.

create table public.workspace_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create schema if not exists private;
revoke all on schema private from public;

create function private.require_tripatra_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email is null or lower(new.email) !~ '^[^@[:space:]]+@tripatra\.com$' then
    raise exception 'Only @tripatra.com email addresses can register for this workspace.' using errcode = '22023';
  end if;

  return new;
end;
$$;

create function private.enroll_tripatra_workspace_member()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  insert into public.workspace_members (user_id, email)
  values (new.id, lower(new.email))
  on conflict (user_id) do update set email = excluded.email;

  return null;
end;
$$;

revoke all on function private.require_tripatra_email() from public, anon, authenticated;
revoke all on function private.enroll_tripatra_workspace_member() from public, anon, authenticated;

create trigger require_tripatra_email
before insert or update of email on auth.users
for each row execute function private.require_tripatra_email();

create trigger enroll_tripatra_workspace_member
after insert or update of email on auth.users
for each row execute function private.enroll_tripatra_workspace_member();

create table public.po_revisions (
  id bigint generated by default as identity primary key,
  po_number text not null,
  revision_number integer not null check (revision_number >= 0),
  released_date date not null,
  purchasing_group text not null check (purchasing_group in ('ELE', 'INS', 'ROT', 'PRO')),
  location text not null check (char_length(location) between 1 and 250),
  equipment_name text not null,
  vendor_name text not null,
  budget numeric(18, 2) not null check (budget >= 0),
  contract_value numeric(18, 2) not null check (contract_value >= 0),
  delivery_lead_time_weeks integer not null check (delivery_lead_time_weeks >= 0),
  incoterm text not null check (incoterm in ('EXW', 'FCA', 'CPT', 'CIP', 'DAP', 'DPU', 'DDP', 'FAS', 'FOB', 'CFR', 'CIF')),
  eta_ros_at_site date not null,
  term_of_payment text not null check (term_of_payment in ('T/T', 'SKBDN')),
  milestone_details text not null default '' check (char_length(milestone_details) <= 2000),
  pb boolean not null,
  pb_validity date,
  wb boolean not null,
  wb_validity date,
  supervision_installation_assist_included boolean not null default false,
  supervision_installation_assist_mandays numeric(12, 2),
  supervision_installation_assist_cost numeric(18, 2),
  precomm_commissioning_assist_included boolean not null default false,
  precomm_commissioning_assist_mandays numeric(12, 2),
  precomm_commissioning_assist_cost numeric(18, 2),
  training_included boolean not null default false,
  training_mandays numeric(12, 2),
  training_cost numeric(18, 2),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint po_revisions_po_revision_unique unique (po_number, revision_number),
  constraint po_revisions_pb_validity_consistency check ((pb and pb_validity is not null) or (not pb and pb_validity is null)),
  constraint po_revisions_wb_validity_consistency check ((wb and wb_validity is not null) or (not wb and wb_validity is null)),
  constraint po_revisions_supervision_installation_assist_consistency check (
    (supervision_installation_assist_included and supervision_installation_assist_mandays is not null and supervision_installation_assist_mandays >= 0 and supervision_installation_assist_cost is not null and supervision_installation_assist_cost >= 0)
    or (not supervision_installation_assist_included and supervision_installation_assist_mandays is null and supervision_installation_assist_cost is null)
  ),
  constraint po_revisions_precomm_commissioning_assist_consistency check (
    (precomm_commissioning_assist_included and precomm_commissioning_assist_mandays is not null and precomm_commissioning_assist_mandays >= 0 and precomm_commissioning_assist_cost is not null and precomm_commissioning_assist_cost >= 0)
    or (not precomm_commissioning_assist_included and precomm_commissioning_assist_mandays is null and precomm_commissioning_assist_cost is null)
  ),
  constraint po_revisions_training_consistency check (
    (training_included and training_mandays is not null and training_mandays >= 0 and training_cost is not null and training_cost >= 0)
    or (not training_included and training_mandays is null and training_cost is null)
  )
);

create index po_revisions_po_number_idx on public.po_revisions (po_number);
create index po_revisions_eta_idx on public.po_revisions (eta_ros_at_site);
create index po_revisions_group_idx on public.po_revisions (purchasing_group);

alter table public.workspace_members enable row level security;
alter table public.po_revisions enable row level security;

grant usage on schema public to authenticated;
grant select on public.workspace_members to authenticated;
grant select, insert, update on public.po_revisions to authenticated;
grant usage, select on sequence public.po_revisions_id_seq to authenticated;

create policy "Members can read their own workspace membership"
on public.workspace_members for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Workspace members can read PO revisions"
on public.po_revisions for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can create PO revisions"
on public.po_revisions for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can update PO revisions"
on public.po_revisions for update to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())))
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
