-- Add execution, payment, service, revision-link, and management-action data
-- without changing the historical PO and bond records already in production.

alter table public.po_revisions
  add column if not exists previous_revision_id bigint references public.po_revisions(id) on delete restrict,
  add column if not exists revision_reason text not null default '';

alter table public.po_revisions
  drop constraint if exists po_revisions_previous_revision_reason_check;

alter table public.po_revisions
  add constraint po_revisions_previous_revision_reason_check
  check (
    previous_revision_id is null
    or (previous_revision_id <> id and length(trim(revision_reason)) > 0)
  );

create index if not exists po_revisions_previous_revision_idx
on public.po_revisions (previous_revision_id);

create table if not exists public.delivery_updates (
  id bigint generated by default as identity primary key,
  po_revision_id bigint not null references public.po_revisions(id) on delete restrict,
  update_date date not null default current_date,
  forecast_eta date,
  actual_ros_date date,
  delivery_status text not null check (delivery_status in (
    'not-started', 'manufacturing', 'ready-to-ship', 'in-transit',
    'arrived-at-site', 'completed', 'cancelled'
  )),
  progress_percent numeric(5, 2) not null default 0
    check (progress_percent between 0 and 100),
  delay_reason text not null default '',
  remarks text not null default '',
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists delivery_updates_po_revision_idx
on public.delivery_updates (po_revision_id);
create index if not exists delivery_updates_latest_idx
on public.delivery_updates (po_revision_id, update_date desc, created_at desc);
create index if not exists delivery_updates_forecast_status_idx
on public.delivery_updates (forecast_eta, delivery_status);

create table if not exists public.payment_milestones (
  id bigint generated by default as identity primary key,
  po_revision_id bigint not null references public.po_revisions(id) on delete restrict,
  sequence_no integer not null check (sequence_no > 0),
  milestone_name text not null check (length(trim(milestone_name)) > 0),
  percentage numeric(7, 4) check (percentage between 0 and 100),
  amount numeric(18, 2) not null check (amount >= 0),
  currency_code text not null check (currency_code in ('IDR', 'USD', 'AUD', 'JPY', 'CNY', 'GBP', 'EUR')),
  planned_invoice_date date,
  planned_payment_date date,
  actual_payment_date date,
  milestone_status text not null default 'planned'
    check (milestone_status in ('planned', 'invoiced', 'paid', 'on-hold')),
  remarks text not null default '',
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_milestones_po_sequence_unique unique (po_revision_id, sequence_no),
  constraint payment_milestones_paid_date_check check (
    milestone_status <> 'paid' or actual_payment_date is not null
  )
);

create index if not exists payment_milestones_po_revision_idx
on public.payment_milestones (po_revision_id);
create index if not exists payment_milestones_schedule_idx
on public.payment_milestones (milestone_status, planned_payment_date);

create table if not exists public.po_services (
  id bigint generated by default as identity primary key,
  po_revision_id bigint not null references public.po_revisions(id) on delete restrict,
  service_type text not null check (service_type in (
    'supervision-installation', 'precomm-commissioning', 'training'
  )),
  included boolean not null default false,
  mandays numeric(12, 2) check (mandays >= 0),
  cost_idr numeric(18, 2) check (cost_idr >= 0),
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint po_services_po_type_unique unique (po_revision_id, service_type),
  constraint po_services_inclusion_values_check check (
    (included and mandays is not null and cost_idr is not null)
    or (not included and mandays is null and cost_idr is null)
  )
);

create index if not exists po_services_po_revision_idx
on public.po_services (po_revision_id);
create index if not exists po_services_type_included_idx
on public.po_services (service_type, included);

insert into public.po_services (
  po_revision_id, service_type, included, mandays, cost_idr,
  created_by, updated_by, created_at, updated_at
)
select id, 'supervision-installation', supervision_installation_assist_included,
  case when supervision_installation_assist_included then supervision_installation_assist_mandays else null end,
  case when supervision_installation_assist_included then supervision_installation_assist_cost else null end,
  created_by, updated_by, created_at, updated_at
from public.po_revisions
on conflict (po_revision_id, service_type) do nothing;

insert into public.po_services (
  po_revision_id, service_type, included, mandays, cost_idr,
  created_by, updated_by, created_at, updated_at
)
select id, 'precomm-commissioning', precomm_commissioning_assist_included,
  case when precomm_commissioning_assist_included then precomm_commissioning_assist_mandays else null end,
  case when precomm_commissioning_assist_included then precomm_commissioning_assist_cost else null end,
  created_by, updated_by, created_at, updated_at
from public.po_revisions
on conflict (po_revision_id, service_type) do nothing;

insert into public.po_services (
  po_revision_id, service_type, included, mandays, cost_idr,
  created_by, updated_by, created_at, updated_at
)
select id, 'training', training_included,
  case when training_included then training_mandays else null end,
  case when training_included then training_cost else null end,
  created_by, updated_by, created_at, updated_at
from public.po_revisions
on conflict (po_revision_id, service_type) do nothing;

create or replace function private.sync_po_revision_services()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  insert into public.po_services (
    po_revision_id, service_type, included, mandays, cost_idr,
    created_by, updated_by, created_at, updated_at
  ) values
    (new.id, 'supervision-installation', new.supervision_installation_assist_included,
      case when new.supervision_installation_assist_included then new.supervision_installation_assist_mandays else null end,
      case when new.supervision_installation_assist_included then new.supervision_installation_assist_cost else null end,
      new.created_by, new.updated_by, new.created_at, new.updated_at),
    (new.id, 'precomm-commissioning', new.precomm_commissioning_assist_included,
      case when new.precomm_commissioning_assist_included then new.precomm_commissioning_assist_mandays else null end,
      case when new.precomm_commissioning_assist_included then new.precomm_commissioning_assist_cost else null end,
      new.created_by, new.updated_by, new.created_at, new.updated_at),
    (new.id, 'training', new.training_included,
      case when new.training_included then new.training_mandays else null end,
      case when new.training_included then new.training_cost else null end,
      new.created_by, new.updated_by, new.created_at, new.updated_at)
  on conflict (po_revision_id, service_type) do update
    set included = excluded.included,
        mandays = excluded.mandays,
        cost_idr = excluded.cost_idr,
        updated_by = excluded.updated_by,
        updated_at = excluded.updated_at;
  return new;
end;
$$;

drop trigger if exists sync_po_revision_services on public.po_revisions;
create trigger sync_po_revision_services
after insert or update of
  supervision_installation_assist_included,
  supervision_installation_assist_mandays,
  supervision_installation_assist_cost,
  precomm_commissioning_assist_included,
  precomm_commissioning_assist_mandays,
  precomm_commissioning_assist_cost,
  training_included,
  training_mandays,
  training_cost
on public.po_revisions
for each row execute function private.sync_po_revision_services();

alter table public.alerts
  add column if not exists due_date date,
  add column if not exists financial_exposure numeric(18, 2) check (financial_exposure >= 0),
  add column if not exists currency_code text check (currency_code in ('IDR', 'USD', 'AUD', 'JPY', 'CNY', 'GBP', 'EUR'));

create index if not exists alerts_owner_due_idx
on public.alerts (assigned_to, due_date)
where alert_status <> 'resolved';

alter table public.delivery_updates enable row level security;
alter table public.payment_milestones enable row level security;
alter table public.po_services enable row level security;

grant select, insert on public.delivery_updates to authenticated;
grant select, insert, update on public.payment_milestones, public.po_services to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on public.delivery_updates, public.payment_milestones, public.po_services from anon;

create policy "Workspace members can read delivery updates"
on public.delivery_updates for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can add delivery updates"
on public.delivery_updates for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can read payment milestones"
on public.payment_milestones for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can add payment milestones"
on public.payment_milestones for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can update payment milestones"
on public.payment_milestones for update to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())))
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can read PO services"
on public.po_services for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can add PO services"
on public.po_services for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can update PO services"
on public.po_services for update to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())))
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

revoke all on function private.sync_po_revision_services() from public, anon;
grant execute on function private.sync_po_revision_services() to authenticated;
