-- Normalized EPC vendor master. Additive migration: public.vendors is retained read-only.
create extension if not exists citext with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create or replace function public.normalize_vendor_name(value text) returns text
language sql immutable strict set search_path = '' as $$
  select trim(regexp_replace(regexp_replace(lower(value), '^\s*pt\.?\s+', ''), '[^[:alnum:]]+', ' ', 'g'));
$$;
revoke all on function public.normalize_vendor_name(text) from public, anon;
grant execute on function public.normalize_vendor_name(text) to authenticated;

create table public.vendor_companies (
 id uuid primary key default gen_random_uuid(), legal_name text not null check (btrim(legal_name) <> ''), display_name text not null check (btrim(display_name) <> ''),
 normalized_name text not null unique, vendor_type text not null default 'other' check (vendor_type in ('manufacturer','distributor','agent','system_integrator','contractor','service_provider','other')),
 country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'), website text, status text not null default 'active' check (status in ('active','inactive','merged')),
 merged_into_vendor_id uuid references public.vendor_companies(id) on delete restrict, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 created_by uuid references auth.users(id) on delete set null, updated_by uuid references auth.users(id) on delete set null,
 check ((status = 'merged') = (merged_into_vendor_id is not null)), check (merged_into_vendor_id is null or merged_into_vendor_id <> id)
);
create table public.vendor_aliases (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendor_companies(id) on delete restrict, alias_name text not null, normalized_alias text not null unique, source text, created_at timestamptz not null default now());
create table public.vendor_contacts (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendor_companies(id) on delete restrict, full_name text, job_title text, country_code text, phone text, is_primary boolean not null default false, active boolean not null default true, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index vendor_contacts_one_active_primary on public.vendor_contacts(vendor_id) where active and is_primary;
create table public.vendor_emails (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendor_companies(id) on delete restrict, contact_id uuid references public.vendor_contacts(id) on delete restrict, email extensions.citext not null, is_primary boolean not null default false, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(vendor_id,email));
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null, normalized_name text not null unique, enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.vendor_categories (vendor_id uuid references public.vendor_companies(id) on delete restrict, category_id uuid references public.categories(id) on delete restrict, primary key(vendor_id,category_id));

-- Expertise may not exist in every legacy deployment; create/upgrade it without discarding rows.
create table if not exists public.expertise (id uuid primary key default gen_random_uuid(), name text not null, enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.expertise add column if not exists normalized_name text;
update public.expertise set normalized_name = public.normalize_vendor_name(name) where normalized_name is null;
create unique index if not exists expertise_normalized_name_unique on public.expertise(normalized_name);
alter table public.expertise alter column normalized_name set not null;
create table public.vendor_expertise (vendor_id uuid references public.vendor_companies(id) on delete restrict, expertise_id uuid references public.expertise(id) on delete restrict, notes text, primary key(vendor_id,expertise_id));
create table public.expertise_aliases (id uuid primary key default gen_random_uuid(), expertise_id uuid not null references public.expertise(id) on delete restrict, alias_name text not null, normalized_alias text not null unique, confirmed boolean not null default false, created_at timestamptz not null default now());
create table public.expertise_migration_review (id uuid primary key default gen_random_uuid(), legacy_vendor_id bigint, raw_value text not null, normalized_value text not null, reason text not null, created_at timestamptz not null default now(), unique(legacy_vendor_id,normalized_value));
create table public.vendor_relationships (id uuid primary key default gen_random_uuid(), vendor_id uuid not null references public.vendor_companies(id) on delete restrict, related_vendor_id uuid not null references public.vendor_companies(id) on delete restrict, relationship_type text not null check (relationship_type in ('distributor_for','agent_for','representative_for','authorized_service_for','system_integrator_for','subsidiary_of')), notes text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(vendor_id,related_vendor_id,relationship_type), check(vendor_id <> related_vendor_id));
create table public.vendor_merge_audit (id uuid primary key default gen_random_uuid(), source_vendor_id uuid not null references public.vendor_companies(id), target_vendor_id uuid not null references public.vendor_companies(id), merged_by uuid not null references auth.users(id), preview jsonb not null, merged_at timestamptz not null default now(), check(source_vendor_id <> target_vendor_id));
create table public.vendor_duplicate_decisions (vendor_id uuid references public.vendor_companies(id), candidate_vendor_id uuid references public.vendor_companies(id), decision text not null check(decision in ('not_duplicate','relationship')), decided_by uuid references auth.users(id), decided_at timestamptz not null default now(), notes text, primary key(vendor_id,candidate_vendor_id));

insert into public.categories(name,normalized_name,sort_order) values ('Electrical','electrical',10),('Instrument','instrument',20),('Telecom','telecom',30),('Mechanical','mechanical',40),('Other','other',50) on conflict(normalized_name) do update set name=excluded.name,sort_order=excluded.sort_order;

-- Immutable point-in-time copy. Revokes and trigger make accidental mutation fail.
create table public.vendors_legacy_snapshot_20260804 as table public.vendors;
revoke all on public.vendors_legacy_snapshot_20260804 from public, anon, authenticated;
create or replace function private.reject_legacy_vendor_change() returns trigger language plpgsql set search_path = '' as $$ begin raise exception 'Legacy vendor data is read-only'; end $$;
revoke all on function private.reject_legacy_vendor_change() from public,anon,authenticated;
create trigger vendors_legacy_read_only before insert or update or delete or truncate on public.vendors for each statement execute function private.reject_legacy_vendor_change();

-- Conservative backfill: exact canonical normalization only; no fuzzy or relationship-based merges.
insert into public.vendor_companies(legal_name,display_name,normalized_name,vendor_type,status,notes)
select min(vendor_name), min(vendor_name), public.normalize_vendor_name(vendor_name), 'other', case when bool_or(is_active) then 'active' else 'inactive' end, 'Migrated from public.vendors; legacy rows retained.'
from public.vendors where nullif(btrim(vendor_name),'') is not null group by public.normalize_vendor_name(vendor_name) on conflict(normalized_name) do nothing;
insert into public.vendor_aliases(vendor_id,alias_name,normalized_alias,source)
select vc.id,v.vendor_name,public.normalize_vendor_name(v.vendor_name),'legacy_migration' from public.vendors v join public.vendor_companies vc on vc.normalized_name=public.normalize_vendor_name(v.vendor_name) where nullif(btrim(v.vendor_name),'') is not null on conflict(normalized_alias) do nothing;

-- Contact/email/category/expertise backfill is schema-adaptive because historic deployments differ.
do $body$ declare pic_col text; phone_col text; emails_col text; category_col text; expertise_col text; sql text; begin
 select column_name into pic_col from information_schema.columns where table_schema='public' and table_name='vendors' and column_name in ('pic','pic_name','contact_person') order by array_position(array['pic','pic_name','contact_person'],column_name) limit 1;
 select column_name into phone_col from information_schema.columns where table_schema='public' and table_name='vendors' and column_name in ('phone','phone_number','telephone') limit 1;
 if pic_col is not null or phone_col is not null then sql := format('insert into public.vendor_contacts(vendor_id,full_name,phone,notes) select vc.id,%s,%s,''Legacy contact'' from public.vendors v join public.vendor_companies vc on vc.normalized_name=public.normalize_vendor_name(v.vendor_name) where nullif(btrim(coalesce(%s,%s)),'''') is not null',case when pic_col is null then 'null' else format('v.%I::text',pic_col) end,case when phone_col is null then 'null' else format('v.%I::text',phone_col) end,case when pic_col is null then '''''' else format('v.%I::text',pic_col) end,case when phone_col is null then '''''' else format('v.%I::text',phone_col) end); execute sql; end if;
 select column_name into emails_col from information_schema.columns where table_schema='public' and table_name='vendors' and column_name in ('emails','email') limit 1;
 if emails_col is not null then execute format($q$insert into public.vendor_emails(vendor_id,email) select distinct vc.id,btrim(e.email)::extensions.citext from public.vendors v join public.vendor_companies vc on vc.normalized_name=public.normalize_vendor_name(v.vendor_name) cross join lateral unnest(regexp_split_to_array(coalesce(v.%I::text,''),'[,;]')) e(email) where btrim(e.email)<>'' on conflict(vendor_id,email) do nothing$q$,emails_col); end if;
 select column_name into category_col from information_schema.columns where table_schema='public' and table_name='vendors' and column_name='category';
 if category_col is not null then execute format($q$insert into public.vendor_categories select distinct vc.id,c.id from public.vendors v join public.vendor_companies vc on vc.normalized_name=public.normalize_vendor_name(v.vendor_name) join public.categories c on c.normalized_name=public.normalize_vendor_name(v.%I::text) on conflict do nothing$q$,category_col); end if;
 select column_name into expertise_col from information_schema.columns where table_schema='public' and table_name='vendors' and column_name='expertise';
 if expertise_col is not null then execute format($q$insert into public.expertise(name,normalized_name) select min(btrim(x.value)),public.normalize_vendor_name(x.value) from public.vendors v cross join lateral unnest(string_to_array(coalesce(v.%I::text,''),';')) x(value) where btrim(x.value)<>'' group by public.normalize_vendor_name(x.value) on conflict(normalized_name) do nothing$q$,expertise_col); execute format($q$insert into public.vendor_expertise select distinct vc.id,e.id,null from public.vendors v join public.vendor_companies vc on vc.normalized_name=public.normalize_vendor_name(v.vendor_name) cross join lateral unnest(string_to_array(coalesce(v.%I::text,''),';')) x(value) join public.expertise e on e.normalized_name=public.normalize_vendor_name(x.value) where btrim(x.value)<>'' on conflict do nothing$q$,expertise_col); end if;
end $body$;

create index on public.vendor_aliases(vendor_id); create index on public.vendor_contacts(vendor_id); create index on public.vendor_emails(vendor_id); create index on public.vendor_emails(contact_id); create index on public.vendor_relationships(related_vendor_id); create index vendor_companies_name_trgm on public.vendor_companies using gin(display_name extensions.gin_trgm_ops);

create or replace function public.search_vendor_company_ids(search_term text) returns table(vendor_id uuid) language sql stable security invoker set search_path='' as $$ select distinct vc.id from public.vendor_companies vc left join public.vendor_aliases va on va.vendor_id=vc.id left join public.vendor_contacts ct on ct.vendor_id=vc.id left join public.vendor_emails em on em.vendor_id=vc.id left join public.vendor_expertise ve on ve.vendor_id=vc.id left join public.expertise ex on ex.id=ve.expertise_id left join public.vendor_relationships vr on vr.vendor_id=vc.id left join public.vendor_companies principal on principal.id=vr.related_vendor_id where concat_ws(' ',vc.legal_name,vc.display_name,va.alias_name,ct.full_name,ct.phone,em.email::text,ex.name,principal.display_name) ilike '%'||replace(search_term,'%','\%')||'%'; $$;
revoke all on function public.search_vendor_company_ids(text) from public,anon; grant execute on function public.search_vendor_company_ids(text) to authenticated;

create or replace function public.merge_vendor_companies(source_id uuid,target_id uuid,expected_source_updated_at timestamptz) returns uuid language plpgsql security definer set search_path='' as $$ declare actor_role text; snapshot jsonb; begin
 if source_id=target_id then raise exception 'Source and target must differ'; end if; select role into actor_role from public.workspace_members where user_id=auth.uid(); if actor_role not in ('admin','editor') then raise exception 'Editor role required' using errcode='42501'; end if;
 perform 1 from public.vendor_companies where id in(source_id,target_id) and status<>'merged' for update; if not found or (select updated_at from public.vendor_companies where id=source_id)<>expected_source_updated_at then raise exception 'Vendor changed; refresh preview'; end if;
 select jsonb_build_object('contacts',(select count(*) from public.vendor_contacts where vendor_id=source_id),'emails',(select count(*) from public.vendor_emails where vendor_id=source_id),'expertise',(select count(*) from public.vendor_expertise where vendor_id=source_id),'categories',(select count(*) from public.vendor_categories where vendor_id=source_id),'relationships',(select count(*) from public.vendor_relationships where vendor_id=source_id)) into snapshot;
 insert into public.vendor_aliases(vendor_id,alias_name,normalized_alias,source) select target_id,legal_name,normalized_name,'merge' from public.vendor_companies where id=source_id on conflict(normalized_alias) do update set vendor_id=target_id;
 update public.vendor_contacts set vendor_id=target_id,updated_at=now() where vendor_id=source_id and not(is_primary and exists(select 1 from public.vendor_contacts where vendor_id=target_id and active and is_primary)); update public.vendor_contacts set is_primary=false,vendor_id=target_id,updated_at=now() where vendor_id=source_id;
 insert into public.vendor_expertise select target_id,expertise_id,notes from public.vendor_expertise where vendor_id=source_id on conflict do nothing; delete from public.vendor_expertise where vendor_id=source_id;
 insert into public.vendor_categories select target_id,category_id from public.vendor_categories where vendor_id=source_id on conflict do nothing; delete from public.vendor_categories where vendor_id=source_id;
 update public.vendor_emails set vendor_id=target_id,updated_at=now() where vendor_id=source_id and not exists(select 1 from public.vendor_emails t where t.vendor_id=target_id and t.email=vendor_emails.email); delete from public.vendor_emails where vendor_id=source_id;
 update public.vendor_relationships set vendor_id=target_id,updated_at=now() where vendor_id=source_id and related_vendor_id<>target_id; update public.vendor_relationships set related_vendor_id=target_id,updated_at=now() where related_vendor_id=source_id and vendor_id<>target_id;
 update public.vendor_companies set status='merged',merged_into_vendor_id=target_id,updated_at=now(),updated_by=auth.uid() where id=source_id; insert into public.vendor_merge_audit(source_vendor_id,target_vendor_id,merged_by,preview) values(source_id,target_id,auth.uid(),snapshot); return target_id; end $$;
revoke all on function public.merge_vendor_companies(uuid,uuid,timestamptz) from public,anon; grant execute on function public.merge_vendor_companies(uuid,uuid,timestamptz) to authenticated;

-- Explicit authenticated RLS; domain admission remains workspace_members/auth trigger responsibility.
do $body$ declare t text; begin foreach t in array array['vendor_companies','vendor_aliases','vendor_contacts','vendor_emails','categories','vendor_categories','expertise','vendor_expertise','expertise_aliases','expertise_migration_review','vendor_relationships','vendor_merge_audit','vendor_duplicate_decisions'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "Workspace members read %s" on public.%I for select to authenticated using (exists(select 1 from public.workspace_members wm where wm.user_id=auth.uid()))',t,t); execute format('create policy "Workspace editors write %s" on public.%I for all to authenticated using ((select private.is_workspace_editor())) with check ((select private.is_workspace_editor()))',t,t); end loop; end $body$;
grant select on public.vendor_companies,public.vendor_aliases,public.vendor_contacts,public.vendor_emails,public.categories,public.vendor_categories,public.expertise,public.vendor_expertise,public.expertise_aliases,public.expertise_migration_review,public.vendor_relationships,public.vendor_merge_audit,public.vendor_duplicate_decisions to authenticated;
grant insert,update,delete on public.vendor_companies,public.vendor_aliases,public.vendor_contacts,public.vendor_emails,public.categories,public.vendor_categories,public.expertise,public.vendor_expertise,public.expertise_aliases,public.expertise_migration_review,public.vendor_relationships,public.vendor_merge_audit,public.vendor_duplicate_decisions to authenticated;
