-- Expand the existing single CM1 workspace with master data, bond history,
-- alert workflow, and dashboard-ready PO fields. Existing rows remain intact.

alter table public.workspace_members
  add column if not exists role text not null default 'editor'
  check (role in ('admin', 'editor'));

-- Preserve current access: the earliest existing member becomes the first admin.
with first_member as (
  select user_id from public.workspace_members order by created_at, user_id limit 1
)
update public.workspace_members
set role = 'admin'
where user_id in (select user_id from first_member)
  and not exists (select 1 from public.workspace_members where role = 'admin');

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  project_code text not null,
  project_name text not null default '',
  is_active boolean not null default true,
  created_by text not null default '',
  updated_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint projects_project_code_unique unique (project_code)
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  vendor_name text not null,
  vendor_code text,
  is_active boolean not null default true,
  created_by text not null default '',
  updated_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vendors_vendor_code_unique unique (vendor_code)
);

create unique index if not exists vendors_vendor_name_unique_idx
on public.vendors (lower(vendor_name));

create table if not exists public.workspace_settings (
  id smallint primary key default 1 check (id = 1),
  delivery_warning_days integer not null default 30 check (delivery_warning_days between 1 and 365),
  bond_critical_days integer not null default 30 check (bond_critical_days between 1 and 365),
  bond_warning_days integer not null default 60 check (bond_warning_days between 1 and 365),
  updated_by text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.workspace_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.po_revisions
  add column if not exists project_id bigint references public.projects(id) on delete restrict,
  add column if not exists vendor_id bigint references public.vendors(id) on delete restrict,
  add column if not exists currency_code text not null default 'IDR' check (currency_code ~ '^[A-Z]{3}$'),
  add column if not exists delivery_completed_at date,
  add column if not exists cancelled_at date,
  add column if not exists responsible_person text,
  add column if not exists revision_review_required boolean not null default false;

insert into public.vendors (vendor_name, created_by, updated_by)
select distinct trim(vendor_name), '', ''
from public.po_revisions
where trim(vendor_name) <> ''
on conflict do nothing;

update public.po_revisions po
set vendor_id = vendor.id
from public.vendors vendor
where po.vendor_id is null
  and lower(vendor.vendor_name) = lower(po.vendor_name);

create table if not exists public.bonds (
  id bigint generated by default as identity primary key,
  po_revision_id bigint not null references public.po_revisions(id) on delete restrict,
  bond_type text not null check (bond_type in ('PB', 'WB')),
  bond_number text,
  issuing_bank text,
  currency_code text not null default 'IDR' check (currency_code ~ '^[A-Z]{3}$'),
  bond_value numeric(18, 2) check (bond_value >= 0),
  required_percentage numeric(7, 4) check (required_percentage >= 0),
  expected_value numeric(18, 2) check (expected_value >= 0),
  received_date date,
  issue_date date,
  effective_date date,
  expiry_date date,
  released_date date,
  supersedes_bond_id bigint references public.bonds(id) on delete restrict,
  replaced_at timestamptz,
  remarks text not null default '',
  attachment_reference text,
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bond_history (
  id bigint generated by default as identity primary key,
  bond_id bigint not null references public.bonds(id) on delete restrict,
  action_type text not null check (action_type in ('created', 'updated', 'received', 'released', 'extended', 'replaced')),
  previous_value jsonb,
  new_value jsonb,
  note text,
  acted_by text not null,
  acted_at timestamptz not null default now()
);

-- Carry forward existing PB/WB validity records without changing the PO fields.
insert into public.bonds (
  po_revision_id, bond_type, received_date, effective_date, expiry_date,
  remarks, created_by, updated_by
)
select id, 'PB', released_date, released_date, pb_validity,
  'Migrated from the existing Performance Bond validity field.', created_by, updated_by
from public.po_revisions po
where po.pb
  and not exists (
    select 1 from public.bonds bond
    where bond.po_revision_id = po.id and bond.bond_type = 'PB'
  );

insert into public.bonds (
  po_revision_id, bond_type, received_date, effective_date, expiry_date,
  remarks, created_by, updated_by
)
select id, 'WB', released_date, released_date, wb_validity,
  'Migrated from the existing Warranty Bond validity field.', created_by, updated_by
from public.po_revisions po
where po.wb
  and not exists (
    select 1 from public.bonds bond
    where bond.po_revision_id = po.id and bond.bond_type = 'WB'
  );

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  po_revision_id bigint references public.po_revisions(id) on delete restrict,
  bond_id bigint references public.bonds(id) on delete restrict,
  priority text not null check (priority in ('critical', 'high', 'medium')),
  alert_type text not null,
  alert_status text not null default 'open' check (alert_status in ('open', 'acknowledged', 'resolved')),
  relevant_date date,
  days_remaining integer,
  assigned_to text,
  note text not null default '',
  created_by text not null default 'system',
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  resolved_by text
);

create table if not exists public.alert_history (
  id bigint generated by default as identity primary key,
  alert_id bigint not null references public.alerts(id) on delete restrict,
  action_type text not null check (action_type in ('created', 'acknowledged', 'resolved', 'updated')),
  previous_value jsonb,
  new_value jsonb,
  note text,
  acted_by text not null,
  acted_at timestamptz not null default now()
);

create index if not exists po_revisions_project_idx on public.po_revisions (project_id);
create index if not exists po_revisions_vendor_idx on public.po_revisions (vendor_id);
create index if not exists po_revisions_currency_idx on public.po_revisions (currency_code);
create index if not exists po_revisions_active_schedule_idx on public.po_revisions (eta_ros_at_site, delivery_completed_at, cancelled_at);
create index if not exists bonds_po_revision_idx on public.bonds (po_revision_id);
create index if not exists bonds_supersedes_bond_idx on public.bonds (supersedes_bond_id);
create index if not exists bonds_type_expiry_idx on public.bonds (bond_type, expiry_date);
create unique index if not exists bonds_active_identity_unique_idx
on public.bonds (po_revision_id, bond_type, bond_number)
where bond_number is not null and replaced_at is null;
create index if not exists alerts_status_priority_idx on public.alerts (alert_status, priority, relevant_date);
create index if not exists alerts_po_revision_idx on public.alerts (po_revision_id);
create index if not exists alerts_bond_idx on public.alerts (bond_id);
create index if not exists bond_history_bond_idx on public.bond_history (bond_id);
create index if not exists alert_history_alert_idx on public.alert_history (alert_id, acted_at desc);

create or replace function private.is_workspace_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members
    where user_id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function private.is_workspace_admin() from public, anon;
grant execute on function private.is_workspace_admin() to authenticated;

alter table public.projects enable row level security;
alter table public.vendors enable row level security;
alter table public.workspace_settings enable row level security;
alter table public.bonds enable row level security;
alter table public.bond_history enable row level security;
alter table public.alerts enable row level security;
alter table public.alert_history enable row level security;

grant select, insert, update on public.projects, public.vendors, public.workspace_settings, public.bonds, public.bond_history, public.alerts, public.alert_history to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on public.projects, public.vendors, public.workspace_settings, public.bonds, public.bond_history, public.alerts, public.alert_history from anon;

create policy "Workspace members can read projects"
on public.projects for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace admins can manage projects"
on public.projects for all to authenticated
using ((select private.is_workspace_admin()))
with check ((select private.is_workspace_admin()));

create policy "Workspace members can read vendors"
on public.vendors for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace admins can manage vendors"
on public.vendors for all to authenticated
using ((select private.is_workspace_admin()))
with check ((select private.is_workspace_admin()));

create policy "Workspace members can read settings"
on public.workspace_settings for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace admins can update settings"
on public.workspace_settings for update to authenticated
using ((select private.is_workspace_admin()))
with check ((select private.is_workspace_admin()));

create policy "Workspace members can read bonds"
on public.bonds for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can create bonds"
on public.bonds for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can update bonds"
on public.bonds for update to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())))
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can read bond history"
on public.bond_history for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can add bond history"
on public.bond_history for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can read alerts"
on public.alerts for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can create alerts"
on public.alerts for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can update alerts"
on public.alerts for update to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())))
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));

create policy "Workspace members can read alert history"
on public.alert_history for select to authenticated
using (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
create policy "Workspace members can add alert history"
on public.alert_history for insert to authenticated
with check (exists (select 1 from public.workspace_members where user_id = (select auth.uid())));
